import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        satoshi: ['Satoshi', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
        urbanist: ['Urbanist', 'Inter', 'system-ui', 'sans-serif'],
        montserrat: ['Montserrat', 'system-ui', 'sans-serif'],
        poppins: ['Poppins', 'system-ui', 'sans-serif'],
      },
      colors: {
        glow: {
          gold: 'var(--glow-gold)',
          'gold-dark': 'var(--glow-gold-dark)',
          'gold-soft': 'var(--glow-gold-soft)',
          'gold-cta': 'var(--glow-gold-cta)',
          text: 'var(--glow-text)',
          'text-muted': 'var(--glow-text-muted)',
          'text-soft': 'var(--glow-text-soft)',
          'text-subtle': 'var(--glow-text-subtle)',
          surface: 'var(--glow-surface)',
          canvas: 'var(--glow-canvas)',
          'bg-base': 'var(--glow-bg-base)',
          'bg-surface': 'var(--glow-bg-surface)',
          'bg-elevated': 'var(--glow-bg-elevated)',
          primary: 'var(--glow-primary)',
          purple: 'var(--glow-purple)',
          'purple-soft': 'var(--glow-purple-soft)',
          secondary: 'var(--glow-secondary)',
          'border-soft': 'var(--glow-border-soft)',
          'inverse-surface': 'var(--glow-inverse-surface)',
          error: 'var(--glow-error)',
          'error-bg': 'var(--glow-error-bg)',
          'hover-surface': 'var(--glow-hover-surface)',
          placeholder: 'var(--glow-placeholder)',
          'gold-selected': 'var(--glow-gold-selected)',
          'avatar-bg': 'var(--glow-avatar-bg)',
          success: 'var(--glow-success)',
          'success-bg': 'var(--glow-success-bg)',
          'success-action': 'var(--glow-success-action)',
          'success-dark': 'var(--glow-success-dark)',
          'neutral-bg': 'var(--glow-neutral-bg)',
          disabled: 'var(--glow-disabled)',
          'promo-border': 'var(--glow-promo-border)',
          'promo-bg-soft': 'var(--glow-promo-bg-soft)',
          'promo-bg-dashboard': 'var(--glow-promo-bg-dashboard)',
          'promo-text': 'var(--glow-promo-text)',
          'promo-accent': 'var(--glow-promo-accent)',
        },
      },
      boxShadow: {
        'glow-sm': 'var(--glow-shadow-sm)',
        'glow-md': 'var(--glow-shadow-md)',
        'glow-lg': 'var(--glow-shadow-lg)',
        'glow-card': 'var(--glow-shadow-card)',
      },
    },
  },
  plugins: [forms],
}
